server.port: 7003

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.xx.microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: Trace

---
spring.profiles: docker

server.port: 8080
spring.datasource:
  url: jdbc:mysql://mysql/review-db
